/* gcc -dM -E preprocess-test.c | grep -v -E '^#define (_|ARG|BADSIG|BC_|BIG_|BUS_|BYTE_|CAST_|CHAR|CHILD_|CLD_|CLK_|COLL_|CPUMON_|E2BIG|EA|EB|EC|ED|EE|EF|EH|EI|EL|EM|EN|EO|EP|EQ|ER|ES|ET|EU|EW|EX|FOOTPRINT|FPE_|FP_|GID_|HTON|ILL_|INT|IOPOL_|IOV_MAX|LINE_|LINK_|LITTLE_|LLONG|LONG_|MAX_|MB_|MINSIG|NAME_MAX|NGROUPS_MAX|NL_|NSIG|NTOH|NULL|NZERO|OFF_|OPEN_|PASS_|PATH_|PDP_|PIPE_|POLL_|PRIO_|PTHREAD_|PTRDIFF_|QUAD_|RAND_|RE_|RLIMIT_|RLIM_|RSIZE_MAX|RUSAGE_|SA_|SCHAR_|SEGV_|SHRT_|SIG|SIZE_|SI_|SSIZE_|SS_|SV_|TRAP_|UCHAR_|UID_|UINT|ULLONG_|ULONG_|UQUAD_|USER_|USHRT_|WAIT_|WAKEMON_|WCHAR_|WCO|WEXIT|WIF|WINT|WNO|WORD_|WSTO|WTER|WUNT|W_|alloca|assert|bcopy|bzero|errno|hton|mem|ntoh|offsetof|ru_|sa_|sig|static_|stp|str|sv_|w_)' */
#define ARRAY_NAME foo
#define ARRAY_TYPE foo
#define ARRAY_EXPECT_TRAIT
#include "../src/array.h"
#define ARRAY_TRAIT bar
#define ARRAY_TO_STRING
#define ARRAY_COMPARE
#include "../src/array.h"
